//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::profile::Entity as Profile;
pub use super::revoked_tokens::Entity as RevokedTokens;
pub use super::task::Entity as Task;
pub use super::user::Entity as User;
